### PR TITLE
Remove authentication extension related developer docs.

### PR DESCRIPTION
**Pull request by varshavaradarajan**

### CODE REVIEW

**Comment by ketan** [comment]
Can you setup redirects instead to avoid broken links and an SEO penalty?

See [this](https://github.com/gocd/developer.go.cd/blob/master/source/writing_go_plugins/notification/version_1_0/stage_status_notification.html) for an example.

Just drop a .html file in place of the .md file with the file I linked above, obviously, you'll have to change the URLs.

**Comment by varshavaradarajan** [comment]
Redirects to what? We don't have any docs related to authentication extension on plugin-api.gocd.org. Anyway, the deprecation period is till next near. Will just add the notice here and fix the broken link.

**Comment by ketan** [comment]
> Redirects to what?

(I blame the bad chai)

Ahh, I see what you're saying.

Should we be adding adequate warnings on these pages that people should use the authorization endpoint instead?

**Comment by varshavaradarajan** [comment]
Yes, adding the deprecation note. Whatever's on the release notes.

**Pull request closed without merging**
